### ISSUE TITLE
[Tutorial, Bug] JSON Parsing Part 1 - Error Handling doesn't mention updating `tokenize()`

### ISSUE THREAD

**Issue by gondolyr** [davimiku/davimiku.github.io#5]
In JSON Parsing Part 1 (<https://blog.davimiku.com/tutorials/json-parsing-rust-1>, [article source code](https://github.com/davimiku/blog.davimiku.com/blob/main/src/pages/tutorials/json-parsing-rust-1.mdx)), the tutorial defines a new error type `TokenizeError` to make `tokenize_null()` work for invalid values. Afterward, the tutorial mentions updating the `make_token()` function, but not the `tokenize()` function. The tests fail at this stage because the types being passed around have changed.

The content should probably be amended in the [Error Handling](https://github.com/davimiku/blog.davimiku.com/blob/main/src/pages/tutorials/json-parsing-rust-1.mdx#error-handling) section of the article around this text:

> Now that `tokenize_null` can fail, so can `make_token`.

Mentioning that `tokenize()` needs to be updated should be mentioned.

**Comment by davimiku** [comment]
Great catch! This is fixed now in fbf9b8bf56cc0885f749fbfa34a87abb09a31b20
